name: Hugo

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.103.0'
          extended: true

      - name: Run Hugo
        run: hugo -D --minify

      - name: rsync deploy
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: public/
          remote_path: /home/tobias/test_releases
          remote_host: 80.216.249.16
          remote_port: 2222
          remote_user: tobias
          remote_key: ${{ secrets.DEPLOY_KEY }}
